### ISSUE TITLE
cargo sweep -i -r -v ~/.cargo stop working

### ISSUE THREAD

**Issue by roland-rollo** [holmgr/cargo-sweep#56] opened 2021-05-21 16:44 UTC
Hi,

I everyday update my crate and do `cargo sweep -i -r -v ~/.cargo` without problems, but today I see this problem:
rustup update && cargo install cargo-update cargo-sweep cargo-todo gitoxide zellij && cargo sweep -i -r -v ~/.cargo
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'

   stable-x86_64-unknown-linux-gnu unchanged - rustc 1.52.1 (9bc8c42bb 2021-05-09)
  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.54.0-nightly (40d230204 2021-05-20)

info: cleaning up downloads & tmp directories
    Updating crates.io index
     Ignored package `cargo-update v7.0.0` is already installed, use --force to override
     Ignored package `cargo-sweep v0.6.1` is already installed, use --force to override
     Ignored package `cargo-todo v0.2.0` is already installed, use --force to override
     Ignored package `gitoxide v0.7.0` is already installed, use --force to override
     Ignored package `zellij v0.11.0` is already installed, use --force to override
     Summary Successfully installed cargo-update, cargo-sweep, cargo-todo, gitoxide, zellij!
thread 'main' panicked at '--time argument missing', /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-sweep-0.6.1/src/main.rs:232:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Something changed in cargo-sweep?

**Comment by phil-opp** [comment] 2021-05-21 17:24
Seems to be a duplicate of https://github.com/holmgr/cargo-sweep/issues/54. A fix was already proposed in #55 .

**Comment by Eh2406** [comment] 2021-05-21 18:10
Also cargo-sweep is not intended for cleaning `~/.cargo`. https://crates.io/crates/cargo-cache is much better for that use case.
cargo-seep is intended for cleaning `/target/` directories within projects.

**Closed** 2022-04-10 13:59 UTC
